apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  #  - infra/cert-manager.yaml
  - infra
  - infra/argocd/argocd-cmd-params-cm-patch.yml
#patches:
#  - path: patch.yaml
#    namePrefix: production-

