---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portal
  namespace: argocd 
spec:
  secretName: portal-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.cloudomega.sytes.net"
  dnsNames:
  - "cloudomega.sytes.net"
  - "*.cloudomega.sytes.net"

