apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cert-manager 
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager
    helm:
      parameters:
      - name: installCRDs
        value: "true"
      - name: replicaCount
        value: "3"
      - name: dns01RecursiveNameserversOnly
        value: "true"
      - name: dns01RecursiveNameservers
        value: 1.1.1.1:53,9.9.9.9:53
    repoURL: https://charts.jetstack.io
    targetRevision: v1.12.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
