
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc


