apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd
  - storage.yaml
  #- https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.yaml
  #- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  
#patches:
#  - path: patch.yaml
#    namePrefix: production-

