apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  #- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - argocd
  - storage.yaml
  - cert-manager.yaml
  - traefik.yaml
  - external.yaml
  - cert-manager.yaml
  - certificate.yaml
  - cert-prod.yaml
  
#patches:
#  - path: path.yaml
#    namePrefix: production-

