apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd
  - storage.yaml
  - cert-manager.yaml
  - kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v2.10/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  - kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v2.10/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
  - traefik.yaml
  - external.yaml
  - cert-manager.yaml
  - certificate.yaml
  - cert-prod.yaml
  
#patches:
#  - path: path.yaml
#    namePrefix: production-

