apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    chart: vault
    helm:
      parameters:
      - name: server.affinity
        value: ""
      - name: server.ha.enabled
        value: "true"
      - name: server.ha.raft.enabled
        value: "true"
      - name: ui.enabled
        value: "true"
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.25.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
