apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oracle
commonLabels:
  type: oracle

resources:
  - nativepg.yaml
  
#patches:
#  - path: path.yaml
#    namePrefix: production-

