apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  type: db

resources:
  - nativepg.yaml
  - cluster.yaml
  
#patches:
#  - path: path.yaml
#    namePrefix: production-

