apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - install.yaml
  #- argocd-cmd-params-cm-patch.yml
  
patches:
  - path: argocd-cmd-params-cm-patch.yml
  - path: argocd-traefik.yml
#    namePrefix: production-
