namespace: oracle
commonLabels:
  type: oracle
resources:
  - secret-store.yaml
secretGenerator:
- name: oci-secret-name 
  files:
  - oracle/fingerprint.txt
  - oracle/priv.pem
generatorOptions:
  disableNameSuffixHash: true
