apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secrets-env
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: SecretStore
    name: ocivault # Must match SecretStore on the cluster
  target:
    name: wpuser # Name for the secret on the cluster
    creationPolicy: Owner
  data:
  - secretKey: key
    remoteRef:
      key: wpuser
