apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ocivault
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.phx.drsmqwceaafi6.abyhqljs4om3ad3cnhtyf4qpcdg5gdobd6jrevwhplbcztizlagsrxwq2hwq
      region: us-phoenix-1
      auth:
        user: ocid1.user.oc1..aaaaaaaasqbbry42bhvemthmaeu5fjo7zs2ct7rkkvr3fa34ooenp54i44ya
        tenancy: ocid1.tenancy.oc1..aaaaaaaaqwofkpakqpdgkvthe3mykfo4zt5uoxlw7kam6xsms4yr6qw46paa
        secretRef:
          privatekey:
            name: oci-secret-name 
            key: priv.pem
          fingerprint:
            name: oci-secret-name 
            key: fingerprint.txt
